<?php

use PHPUnit\Framework\TestCase;
use Vrkansagara\Dynamodb\DynamoDBService;

class DynamoDBServiceTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testDynamoDBServiceTest()
    {
        $dynamoDBService   = new DynamoDBService();
        $this->assertInstanceOf(DynamoDBService::class, $dynamoDBService);
    }
}
